language: "python"
python: 2.7
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    irc: "chat.freenode.net#cloudrift"
    use_notice: true
    skip_join: true